version: 0.2

env:
  variables:
    VERSION: "3.1"  # Định nghĩa phiên bản

phases:
  pre_build:
    commands:
      - echo Connecting to Amazon ECR...
      - aws --version
      - docker --version
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 689890720727.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=689890720727.dkr.ecr.ap-southeast-1.amazonaws.com/ci-ecr
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$VERSION
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --platform linux/amd64 -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG 

